apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-aurashop
  namespace: aurashop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-aurashop
  template:
    metadata:
      labels:
        app: frontend-aurashop
    spec:
      containers:
        - name: frontend
          image: wilsondacosta/aurashop-frontend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: VITE_API_URL
            - name: VITE_ORDER_API
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: VITE_ORDER_API
            - name: VITE_PAYMENT_API
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: VITE_PAYMENT_API
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-aurashop
  namespace: aurashop
spec:
  type: NodePort
  selector:
    app: frontend-aurashop
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30173
