apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kasir
  template:
    metadata:
      labels:
        app: kasir
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo "waiting mysql..."; sleep 2; done;']

      containers:
        - name: kasir
          image: kasir-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4002
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
          env:
            - name: ORDER_URL
              value: http://order:5001/api/orders
          command: ["npm", "run", "dev"]
---
apiVersion: v1
kind: Service
metadata:
  name: kasir
spec:
  type: NodePort
  selector:
    app: kasir
  ports:
    - port: 4002
      targetPort: 4002
      nodePort: 30003
